In [1]:
import pandas as pd

In [2]:
# import the dataset 

df = pd.read_csv("zomato.csv")

df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

(51717, 17)

In [3]:
#there are a lot of null values in the dataset that needs to be handled
df.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [4]:
df.head(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

### Removing irrelevant and high-noise features like URLs, text-heavy columns (reviews, menu items) and redundant columns to focus on structured attributes that impact restaurant performance.

In [5]:
columns_to_drop = ['url','phone','address','reviews_list', 'menu_item', 'location','rest_type']
df.drop(columns=columns_to_drop, inplace=True)

### Renaming columns for better understandings

In [6]:
df.rename(columns={
    'listed_in(type)': 'restaurant_type',
    'approx_cost(for two people)' : 'cost_for_two',
    'rate' : 'rating',
    'listed_in(city)' : 'location'
}, inplace=True)

### Changing data types 
#### 1. 'rating' column 
it is in format (X/5) string type we will make it float type with X only

In [7]:
#dropping columns with NaN or some other value

df = df[df['rating'].notnull()]              # remove NaN
df = df[~df['rating'].isin(['NEW', '-'])]   # remove invalid strings

In [8]:
#Split the string by '/', select the first part and then convert it to float type 

df['rating'] = df['rating'].str.split('/').str[0].astype(float)

In [9]:
df.head(3)

,name,online_order,book_table,rating,votes,dish_liked,cuisines,cost_for_two,restaurant_type,location
0,Jalsa,Yes,Yes,4.1,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari

In [10]:
df['cost_for_two'].unique()

array(['800', '300', '600', '700', '550', '500', '450', '650', '400',
       '900', '200', '750', '150', '850', '100', '1,200', '350', '250',
       '950', '1,000', '1,500', '1,300', '199', '1,100', '1,600', '230',
       '130', '1,700', '1,350', '2,200', '1,400', '2,000', '1,800', nan,
       '1,900', '180', '330', '2,500', '2,100', '3,000', '2,800', '3,400',
       '50', '40', '1,250', '3,500', '4,000', '2,400', '2,600', '1,450',
       '70', '3,200', '240', '6,000', '1,050', '2,300', '4,100', '120',
       '5,000', '3,700', '1,650', '2,700', '4,500', '80'], dtype=object)

### Cleaning the cost_for_two column 
1. removing null valued rows from dataframe
2. removing ',' from the values
3. changing string to float

In [11]:
df = df[df['cost_for_two'].notnull()]

In [12]:
df['cost_for_two'] = df['cost_for_two'].str.replace(',', '')

In [13]:
df['cost_for_two'] = df['cost_for_two'].astype(float)

In [14]:
df['cost_for_two'].unique()

array([ 800.,  300.,  600.,  700.,  550.,  500.,  450.,  650.,  400.,
        900.,  200.,  750.,  150.,  850.,  100., 1200.,  350.,  250.,
        950., 1000., 1500., 1300.,  199., 1100., 1600.,  230.,  130.,
       1700., 1350., 2200., 1400., 2000., 1800., 1900.,  180.,  330.,
       2500., 2100., 3000., 2800., 3400.,   50.,   40., 1250., 3500.,
       4000., 2400., 2600., 1450.,   70., 3200.,  240., 6000., 1050.,
       2300., 4100.,  120., 5000., 3700., 1650., 2700., 4500.,   80.])

In [15]:
# feature engineering 

# 1. 
df['cost_category'] = pd.cut(
    df['cost_for_two'],
    bins=[0, 500, 1500, 10000],
    labels=['Budget', 'Mid-Range', 'Premium']
)

In [16]:
# 2.

df['rating_category'] = pd.cut(
    df['rating'],
    bins=[0, 3, 4, 5],
    labels=['Poor', 'Good', 'Excellent']
)

In [17]:
#Standardize Yes/No Columns

df['online_order'] = df['online_order'].str.strip()
df['book_table'] = df['book_table'].str.strip()

In [18]:
#Fill Missing Values

df['dish_liked'] = df['dish_liked'].fillna('Not Specified')
df['cuisines'] = df['cuisines'].fillna('Unknown')

In [19]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41418 entries, 0 to 51716
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             41418 non-null  object
 1   online_order     41418 non-null  object
 2   book_table       41418 non-null  object
 3   rating           41418 non-null  float64
 4   votes            41418 non-null  int64
 5   dish_liked       41418 non-null  object
 6   cuisines         41418 non-null  object
 7   cost_for_two     41418 non-null  float64
 8   restaurant_type  41418 non-null  object
 9   location         41418 non-null  object
 10  cost_category    41418 non-null  category
 11  rating_category  41418 non-null  category
dtypes: category(2), float64(2), int64(1), object(7)
memory usage: 3.6+ MB

In [20]:
df.head(10)

,name,online_order,book_table,rating,votes,dish_liked,cuisines,cost_for_two,restaurant_type,location,cost_category,rating_category
0,Jalsa,Yes,Yes,4.1,775,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,Buffet,Banashankari,Mid-Range,Excellent
1,Spice Elephant,Yes,No,4.1,787,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,Buffet,Banashankari,Mid-Range,Excellent
2,San Churro Cafe,Yes,No,3.8,918,"Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,Buffet,Banashankari,Mid-Range,Good
3,Addhuri Udupi Bhojana,No,No,3.7,88,Masala Dosa,"South Indian, North Indian",300.0,Buffet,Banashankari,Budget,Good
4,Grand Village,No,No,3.8,166,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,Buffet,Banashankari,Mid-Range,Good
5,Timepass Dinner,Yes,No,3.8,286,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600.0,Buffet,Banashankari,Mid-Range,Good
6,Rosewood International Hotel - Bar & Restaurant,No,No,3.6,8,Not Specified,"North Indian, South Indian, Andhra, Chinese",800.0,Buffet,Banashankari,Mid-Range,Good
7,Onesta,Yes,Yes,4.6,2556,"Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600.0,Cafes,Banashankari,Mid-Range,Excellent
8,Penthouse Cafe,Yes,No,4.0,324,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700.0,Cafes,Banashankari,Mid-Range,Good
9,Smacznego,Yes,No,4.2,504,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550.0,Cafes,Banashankari,Mid-Range,Excellent

In [21]:
# Export the cleaned data into a csv file
df.to_csv("zomato_cleaned.csv", index=False)